### ISSUE TITLE
Contributing link in README 404's

### ISSUE THREAD

**Issue by TimTaylor** [epiverse-connect/ctv-analysis#35]
The contributing link in the README currently 404's as the associated doc is not present.
https://github.com/epiverse-connect/ctv-analysis/blob/5e235529d9abbd119885b2f8794222096411d86d/README.md?plain=1#L22

**Comment by Bisaloo** [comment]
Thanks for the report! It is fixed by https://github.com/epiverse-connect/ctv-analysis/commit/83923371cc00dbc776753019483431d6d764da4b.
